platform :ios, "16.4"

#source "https://github.com/CocoaPods/Specs.git"

target "KeyPointCenter" do
  use_modular_headers!
  
  pod 'Moya'
  pod 'HandyJSON'
  #pod 'WoodPeckeriOS', :configurations => ['Debug']
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    # Fix Xcode 14 bundle code signing issue
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end

  end
end
